/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:d9ade17c-9b01-4be2-813f-67134069b169',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_fYzfZDPbb',
  aws_user_pools_web_client_id: '566u2lgid0rgrgka04u84ub1ka',
  oauth: {},
  predictions: {
    convert: {
      transcription: {
        region: 'us-east-1',
        proxy: false,
        defaults: {
          language: 'en-GB',
        },
      },
    },
  },
};

export default awsmobile;
